name: macOS Intel x86_64

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-15-intel

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        compiler: [dmd, ldc]

    steps:
      - uses: actions/checkout@v4

      # --- dub をインストール ---
      - name: Install dub
        run: |
          brew update
          brew install dub
          dub --version

      - name: Install latest DMD
        if: matrix.compiler == 'dmd'
        run: |
          brew install dmd
          dmd --version

      - name: Install LDC
        if: matrix.compiler == 'ldc'
        run: |
          brew install ldc
          ldc2 --version

      - name: Run tests
        run: |
          dub test -ax86_64 --parallel -b=unittest-cov